import Link from "next/link";
import { BookOpen, Boxes, CircleCheck, FileCode2, FolderTree, GitFork, Layers, Play, Route, Sparkles, Workflow } from "lucide-react";
import { AnalysisGate } from "@/components/repo/analysis-gate";
import { Badge, Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/primitives";
import { explorerHref } from "@/lib/citations";
import { getLatestAnalysis } from "@/lib/data";
import { CODE_LANGUAGES, displayLanguage } from "@/lib/repo/languages";
import { loadRepository } from "@/lib/repo-page";

export const metadata = { title: "Repository overview" };

function Confirmed() {
  return (
    <Badge variant="success" title="Extracted deterministically by static analysis">
      <CircleCheck /> Confirmed
    </Badge>
  );
}

function Inferred() {
  return (
    <Badge variant="violet" title="Generated by the AI model from repository evidence - verify before relying on it">
      <Sparkles /> AI inference
    </Badge>
  );
}

function FileLink({ repoId, path }: { repoId: string; path: string }) {
  return (
    <Link href={explorerHref(repoId, { path, startLine: 0, endLine: 0 })} className="font-mono text-xs text-primary hover:underline">
      {path}
    </Link>
  );
}

export default async function RepositoryOverviewPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { repo, gate, ready } = await loadRepository(id);
  if (!ready) return <AnalysisGate id={repo.id} initial={gate} />;
  const analysis = await getLatestAnalysis(repo.id);
  if (!analysis) return <AnalysisGate id={repo.id} initial={{ ...gate, status: "failed", error: "No analysis results were stored. Retry the analysis." }} />;

  const { summary, technology_stack: stack, facts, dependency_data: deps } = analysis;
  const languages = Object.entries(repo.languages ?? {}).sort((a, b) => b[1] - a[1]);
  const codeLangTotal = languages.filter(([l]) => CODE_LANGUAGES.has(l)).reduce((n, [, c]) => n + c, 0);
  const docRatio = facts.docs.codeFiles ? Math.round((facts.docs.filesWithDocComments / facts.docs.codeFiles) * 100) : 0;
  const skipped = Object.entries(facts.skipped ?? {}).filter(([, n]) => n > 0);

  return (
    <div className="grid gap-6 lg:grid-cols-3">
      <div className="space-y-6 lg:col-span-2">
        <Card>
          <CardHeader className="flex-row items-start justify-between gap-3">
            <div>
              <CardTitle className="flex items-center gap-2"><BookOpen className="size-4 text-primary" /> Project purpose</CardTitle>
              <CardDescription>Interpretation of the README, structure and key files.</CardDescription>
            </div>
            <Inferred />
          </CardHeader>
          <CardContent className="space-y-3 text-sm leading-relaxed">
            {summary.error || !summary.purpose ? (
              <p className="text-muted-foreground">{summary.error ?? "No AI summary is available."} Confirmed facts below are still accurate.</p>
            ) : (
              <>
                <p className="font-medium">{summary.purpose}</p>
                <p className="text-muted-foreground">{summary.overview}</p>
              </>
            )}
          </CardContent>
        </Card>

        <div className="grid gap-6 md:grid-cols-2">
          <Card>
            <CardHeader className="flex-row items-start justify-between">
              <CardTitle className="flex items-center gap-2"><Play className="size-4 text-primary" /> Entry points</CardTitle>
              <Confirmed />
            </CardHeader>
            <CardContent>
              {facts.entryPoints.length === 0 ? (
                <p className="text-sm text-muted-foreground">No conventional entry points detected.</p>
              ) : (
                <ul className="space-y-2.5">
                  {facts.entryPoints.slice(0, 8).map((e) => (
                    <li key={e.path}>
                      <FileLink repoId={repo.id} path={e.path} />
                      <p className="text-xs text-muted-foreground">{e.reason}</p>
                    </li>
                  ))}
                </ul>
              )}
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex-row items-start justify-between">
              <CardTitle className="flex items-center gap-2"><FileCode2 className="size-4 text-primary" /> Important files</CardTitle>
              <Confirmed />
            </CardHeader>
            <CardContent>
              <ul className="space-y-2.5">
                {facts.importantFiles.slice(0, 8).map((f) => (
                  <li key={f.path}>
                    <FileLink repoId={repo.id} path={f.path} />
                    <p className="text-xs text-muted-foreground">{f.reason}</p>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        </div>

        {summary.keyModules && summary.keyModules.length > 0 && (
          <Card>
            <CardHeader className="flex-row items-start justify-between">
              <CardTitle className="flex items-center gap-2"><Boxes className="size-4 text-primary" /> Main modules</CardTitle>
              <Inferred />
            </CardHeader>
            <CardContent>
              <ul className="grid gap-3 sm:grid-cols-2">
                {summary.keyModules.map((m) => (
                  <li key={m.path} className="rounded-lg border border-border p-3">
                    <FileLink repoId={repo.id} path={m.path} />
                    <p className="mt-1 text-xs text-muted-foreground">{m.description}</p>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        )}

        {summary.workflows && summary.workflows.length > 0 && (
          <Card>
            <CardHeader className="flex-row items-start justify-between">
              <CardTitle className="flex items-center gap-2"><Workflow className="size-4 text-primary" /> Potential workflows</CardTitle>
              <Inferred />
            </CardHeader>
            <CardContent className="space-y-3">
              {summary.workflows.map((w) => (
                <div key={w.name} className="rounded-lg border border-border p-3">
                  <div className="flex flex-wrap items-center justify-between gap-2">
                    <p className="text-sm font-medium">{w.name}</p>
                    <Link href={`/repositories/${repo.id}/chat?q=${encodeURIComponent(`Trace the "${w.name}" workflow and show it as a diagram.`)}`} className="text-xs text-primary hover:underline">
                      Trace with AI
                    </Link>
                  </div>
                  <p className="mt-1 text-xs text-muted-foreground">{w.description}</p>
                  <div className="mt-2 flex flex-wrap gap-x-3 gap-y-1">{w.files.map((f) => <FileLink key={f} repoId={repo.id} path={f} />)}</div>
                </div>
              ))}
            </CardContent>
          </Card>
        )}

        <Card>
          <CardHeader className="flex-row items-start justify-between">
            <CardTitle className="flex items-center gap-2"><Route className="size-4 text-primary" /> Routes</CardTitle>
            <Confirmed />
          </CardHeader>
          <CardContent>
            {facts.routes.length === 0 ? (
              <p className="text-sm text-muted-foreground">No page or API routes detected.</p>
            ) : (
              <div className="max-h-72 overflow-auto rounded-lg border border-border">
                <table className="w-full text-xs">
                  <thead className="sticky top-0 bg-muted text-left text-muted-foreground">
                    <tr><th className="px-3 py-2 font-medium">Route</th><th className="px-3 py-2 font-medium">Type</th><th className="px-3 py-2 font-medium">File</th></tr>
                  </thead>
                  <tbody className="divide-y divide-border">
                    {facts.routes.slice(0, 100).map((r, i) => (
                      <tr key={`${r.path}-${r.route}-${i}`}>
                        <td className="px-3 py-1.5 font-mono">{r.route}</td>
                        <td className="px-3 py-1.5"><Badge variant={r.kind === "api" ? "cyan" : "default"}>{r.kind}</Badge></td>
                        <td className="px-3 py-1.5"><FileLink repoId={repo.id} path={r.path} /></td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      <div className="space-y-6">
        <Card>
          <CardHeader className="flex-row items-start justify-between">
            <CardTitle className="flex items-center gap-2"><Layers className="size-4 text-primary" /> Technology stack</CardTitle>
            <Confirmed />
          </CardHeader>
          <CardContent>
            <ul className="space-y-2">
              {stack.map((t) => (
                <li key={t.name} className="flex items-start justify-between gap-2 text-sm">
                  <span className="font-medium">{t.name}</span>
                  <span className="text-right text-xs text-muted-foreground" title={t.evidence}>{t.category}</span>
                </li>
              ))}
              {stack.length === 0 && <li className="text-sm text-muted-foreground">No known frameworks detected.</li>}
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Languages</CardTitle>
            <CardDescription>{repo.file_count} indexed files · {repo.chunk_count} code chunks</CardDescription>
          </CardHeader>
          <CardContent className="space-y-2">
            {languages.filter(([l]) => CODE_LANGUAGES.has(l)).slice(0, 6).map(([l, n]) => (
              <div key={l}>
                <div className="flex justify-between text-xs"><span>{displayLanguage(l)}</span><span className="tabular-nums text-muted-foreground">{n}</span></div>
                <div className="mt-1 h-1.5 rounded-full bg-muted"><div className="h-full rounded-full bg-primary/70" style={{ width: `${(n / Math.max(codeLangTotal, 1)) * 100}%` }} /></div>
              </div>
            ))}
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex-row items-start justify-between">
            <CardTitle className="flex items-center gap-2"><FolderTree className="size-4 text-primary" /> Directory overview</CardTitle>
            <Confirmed />
          </CardHeader>
          <CardContent>
            <ul className="space-y-1 font-mono text-xs">
              {facts.directories.slice(0, 12).map((d) => (
                <li key={d.path} className="flex justify-between gap-2"><span className="truncate">{d.path}</span><span className="text-muted-foreground">{d.files}</span></li>
              ))}
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex-row items-start justify-between">
            <CardTitle className="flex items-center gap-2"><GitFork className="size-4 text-primary" /> Dependencies</CardTitle>
            <Confirmed />
          </CardHeader>
          <CardContent className="space-y-3">
            {deps.manifests.length === 0 && <p className="text-sm text-muted-foreground">No package manifests found.</p>}
            {deps.manifests.map((m) => (
              <div key={m.path}>
                <FileLink repoId={repo.id} path={m.path} />
                <p className="text-xs text-muted-foreground">{m.dependencies.length} runtime · {m.devDependencies.length} dev</p>
                <div className="mt-1.5 flex flex-wrap gap-1">
                  {m.dependencies.slice(0, 12).map((d) => <span key={d} className="rounded border border-border px-1.5 py-0.5 font-mono text-[10px] text-muted-foreground">{d}</span>)}
                </div>
              </div>
            ))}
            {typeof deps.edgeCount === "number" && <p className="text-xs text-muted-foreground">{deps.edgeCount} internal import relationships resolved.</p>}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Documentation coverage</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2 text-sm">
            <p className="flex justify-between"><span className="text-muted-foreground">README</span><span>{facts.docs.readme ? "Present" : "Missing"}</span></p>
            <p className="flex justify-between"><span className="text-muted-foreground">Markdown files</span><span>{facts.docs.markdownFiles}</span></p>
            <p className="flex justify-between"><span className="text-muted-foreground">Code files with doc comments</span><span>{docRatio}%</span></p>
            {summary.documentationNotes && <p className="border-t border-border pt-2 text-xs text-muted-foreground"><span className="font-medium text-violet">AI note: </span>{summary.documentationNotes}</p>}
          </CardContent>
        </Card>

        {(skipped.length > 0 || facts.truncated || (facts.parseFailures?.length ?? 0) > 0 || (facts.redactions ?? 0) > 0) && (
          <Card>
            <CardHeader><CardTitle>Ingestion notes</CardTitle></CardHeader>
            <CardContent className="space-y-1 text-xs text-muted-foreground">
              {skipped.map(([reason, n]) => <p key={reason}>Skipped {n} file(s): {reason.replace("_", " ")}</p>)}
              {facts.truncated && <p className="text-warning">File limit reached; some files were not indexed.</p>}
              {(facts.redactions ?? 0) > 0 && <p>{facts.redactions} potential secret(s) redacted.</p>}
              {facts.parseFailures?.length > 0 && <p>{facts.parseFailures.length} file(s) could not be parsed (indexed as plain text).</p>}
              {facts.embeddings === false && <p>Embeddings not configured: search uses keyword and symbol matching.</p>}
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}
